### ISSUE TITLE
weather overlays does not work

### ISSUE THREAD

**Issue by ozziepadilla** [JohnCoates/Aerial#1184]
#### General troubleshooting tips
I have the latest version and since the previews the wether on the overlays shows an error and can not be display it iMac late 2013 with macOS Big Sur 11.4 see the attachment 

![Screen Shot 2021-06-27 at 1 58 01 PM](https://user-images.githubusercontent.com/78187370/123554792-c1dff400-d74f-11eb-9933-40f3ad813dc5.png)

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment]
Hey @ozziepadilla 

Based on your screenshot this is not Aerial's latest version. 

Yahoo! disabled their weather API so I released newer versions which use OpenWeather. Please get latest from either this (if you want auto updates) : 

https://github.com/glouel/AerialCompanion/releases/latest/download/AerialCompanion.dmg

or (just the saver) : 

https://github.com/JohnCoates/Aerial/releases/download/v2.3.3/Aerial.saver.zip

**Comment by ozziepadilla** [comment]
I did did load v2.3.3 but inside of Aerial settings I find out that it says v2.2.6 after I ran v2.3.3 which shows me yahoo weather still

**Comment by ozziepadilla** [comment]
oh I see what you said well I do not want aerial companion because that will install another app and I do not want it I have use aerial from system preferences

**Comment by ozziepadilla** [comment]
by the way from the second link still show power by yahoo weather and not the other Openweather you told me

**Comment by glouel** [comment]
It's fine not to install Aerial Companion, but you must close System Preferences (the entire window) after installing 2.3.3, so it loads up again. 

It's a bug with macOS, you should see 2.3.3 afterwards.

**Comment by ozziepadilla** [comment]
is exactly what I did but still power by yahoo weather is there take a look
![Screen Shot 2021-06-27 at 2 35 22 PM](https://user-images.githubusercontent.com/78187370/123555659-0cb03a80-d755-11eb-916f-dd6f9aba3924.png)
![Screen Shot 2021-06-27 at 2 35 40 PM](https://user-images.githubusercontent.com/78187370/123555664-0fab2b00-d755-11eb-9c6f-4dc3a014872f.png)

**Comment by glouel** [comment]
Ok so make sure you don't have two Aerials, check this screen and check if you only have one there : 

<img width="893" alt="Capture d’écran 2021-06-27 à 20 38 34" src="https://user-images.githubusercontent.com/37544189/123555710-a55fae00-d787-11eb-8165-469aefe5eb09.png">

If you have two, remove both, then reinstall using the 2.3.3 link (the second one) from my message above. Close System Preferences BEFORE double installing 2.3.3.

**Comment by ozziepadilla** [comment]
yeah it shows two but I double check before delete it but I did delete both then I reinstall it again and I get the new weather overlays 
![Screen Shot 2021-06-27 at 2 44 21 PM](https://user-images.githubusercontent.com/78187370/123555834-328a0f00-d756-11eb-99c0-755318f28176.png)

**Comment by ozziepadilla** [comment]
> Ok so make sure you don't have two Aerials, check this screen and check if you only have one there :
> 
> <img alt="Capture d’écran 2021-06-27 à 20 38 34" width="893" src="https://user-images.githubusercontent.com/37544189/123555710-a55fae00-d787-11eb-8165-469aefe5eb09.png">
> 
> If you have two, remove both, then reinstall using the 2.3.3 link (the second one) from my message above. Close System Preferences BEFORE double installing 2.3.3.
> 
> Edit : Basically you can have the same screensaver installed twice for weird reasons with macOS, once for "all users" and once for your own user... bit of a weird thing but it causes many issues

yeah I did that thank you

**Comment by ozziepadilla** [comment]
thank you very much for the new weather overlays because I have notice that suddenly yahoo weather disappears from the screen saver

**Comment by glouel** [comment]
Yeah just to clarify, once System Preferences loads one, if you click one or the other, it will only show the first one you clicked. That's a longstanding macOS bug that was reported years ago and it causes a lot of issues (on top of yours). Glad to see you fixed your issue. Take care.
