### ISSUE TITLE
"You cannot use the Aerial screen saver with this version of OS X"

### ISSUE THREAD

**Issue by danielsamuels** [JohnCoates/Aerial#4]
![](https://i.imgur.com/knS90qB.png)

![](https://i.imgur.com/N3RoK8n.png)

**Comment by TuncTaylan** [comment]
How about go ahead and update your os to the release version. It is working fine on 10.11.1.

**Comment by danielsamuels** [comment]
Thanks for the suggestion. You should work on your tone when speaking to people in issue comments, you come across as very aggressive and it's quite unnecessary.

**Comment by TuncTaylan** [comment]
Yes, I'm sorry. I've noticed it too, after I've typed it... didn't mean anything negative or aggressive actually.

Sorry again.

**Comment by bonny** [comment]
I have 10.11.1 (15B42) and I get the same message.

**Comment by Cataklix** [comment]
me too

**Comment by jamesfoley** [comment]
Working fine for me on 10.11.1 (15B42)

**Comment by DJay1** [comment]
Strange. I'm on 10.11.1 (15B42) as well and here everything works as expected. Great project by the way. Would be cool to see configuration possibility that the night views only show after sunset or a specific time.

**Comment by TuncTaylan** [comment]
How did you build it? Which version of Xcode?

**Comment by DomingoCP** [comment]
I am having the same issue with 10.11.1 (15B42).

**Comment by ryck** [comment]
I am getting the same error in OSX 10.10.4, using the precompiled saver.

**Comment by TuncTaylan** [comment]
Maybe the following will help debug the issue:

Type in the console "open /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app" to activate the screensaver. Be sure it is selected beforehand.
And grep your system.log for ScreenSaverEngine and post it here:
tail -f /var/log/system.log|grep ScreenSaverEngine

**Comment by ryck** [comment]
Weird: now it works, but I haven't done anything yet...

**Comment by bonny** [comment]
Wierd! It works for me too now. Perhaps you need to close the screensaver-preferences pane, browse some random pages, then open up the preferences pane again? :)

Now I also get the button "Screen saved options", it was dimmed before.

**Comment by JohnCoates** [comment]
That is seriously weird!

**Comment by DomingoCP** [comment]
If I open it with "open /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app" it works, but then If I preview/activate it from system preferences it goes black again.

**Comment by llahnoraa** [comment]
It worked fine on 10.11.1 (15B42). Great job!!!

**Comment by mrabrams** [comment]
In case it helps someone, it seems Little Snitch is blocking internet access by default, making it so the screensaver just shows a white screen.

**Comment by shaungrady** [comment]
Not working for me, says "You cannot use the Aerial screen saver with this version of OS X"
>
MacBook Pro (Retina, Mid 2012)
OS X 10.11.1 (15B42)
2x external monitors (if that's of any consequence)

**Comment by br-ad** [comment]
To get this to work, I set it as the screensaver (even though it said it wasn't compatible) closed the preferences, opened it back up and it worked. 10.11.1

**Comment by shaungrady** [comment]
No such luck in my case

**Comment by macbookandrew** [comment]
:+1: for what @br-ad said.

iMac 21.5", late 2013
OS X 10.11.1 (15B42)
one external monitor

**Comment by llahnoraa** [comment]
Off topic but triple monitors worked flawlessly.

**Comment by alistairmcmillan** [comment]
@danielsamuels @Cataklix @DomingoCP @ryck @shaungrady Did you get the screensaver to work?

**Comment by shaungrady** [comment]
I no longer have access to the machine it was broken on, so I can't report.

**Comment by alistairmcmillan** [comment]
This "cannot use the Aerial screen saver with this version of OS X" error is caused by a bug in OS X.

http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by AlexPasternak** [comment]
Would be great to have this fixed. Broken for me on El Capitan 10.11.6.

**Comment by alistairmcmillan** [comment]
@AlexPasternak Select Aerial, close System Preferences, re-open System Preferences, the preview should now work. Let us know if it doesn't.

I logged a bug with Apple about it ten months ago but they haven't responded. radr://25569037 for anyone that's interested.

**Comment by AlexPasternak** [comment]
I was almost about to post that it didn't work, because I closed SP and went back in, but I missed the fact that you said select this screensaver, then exit, then re-open. That did the trick, thanks.

I wish there was a "Me too" button for Apple bugs like there is for Sonos sw issues, for example. Or any sort of a vote, really.

**Comment by fahimisediqa** [comment]
I get the same error. I'm using 10.12.3

**Comment by alistairmcmillan** [comment]
@fahimisediqa 

1) Open System Preferences and select Aerial.
2) Leave Aerial selected and close System Preferences.
3) Reopen System Preferences, the error should be gone.

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan, @JohnCoates, after alistair's previous comment I did some experimentation. Does not solve the underlying problem, but does create a solution where users will not have the issue any longer. relates to #349 

<pre>
defaults -currentHost write com.apple.screensaver modulePath -string "/System/Library/Screen Savers/Shell.saver"; defaults -currentHost write com.apple.screensaver moduleName -string "Shell"; defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName Shell path /System/Library/Screen\ Savers/Shell.saver/ type 0


defaults -currentHost write com.apple.screensaver modulePath -string "~/Library/Screen\ Savers/Aerial.saver"; defaults -currentHost write com.apple.screensaver moduleName -string "Aerial";defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName Aerial path ~/Library/Screen\ Savers/Aerial.saver type 0

/System/Library/Frameworks/ScreenSaver.framework/Resources/./ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background;
</pre>

These are terminal commands. As terminal commands they are not very useful because as Alistair mentioned a user could manually close and reopen System Preferences. However, if incorporated into Aerial.saver as commands at the end. Then users should no longer see the problem and the fix will be automatically handled. Another benefit would be Aerial would by default be the screensaver. Which was the goal of #349.

**Comment by alistairmcmillan** [comment]
As I mentioned on another issue. If these commands were incorporated into the screensaver, the only way for them to take effect is for the screensaver to run. And if the screensaver is running, then people don't see this error.

Or to phrase it the other way around. This error means that macOS couldn't run the screensaver. If it can't run the screensaver then the commands wouldn't run.

The only way to fix this right now is by nagging Apple to get them to fix the bug in macOS.

**Comment by MichaelDimmitt** [comment]
@alistairmcmillan, "Aerial.saver" currently runs and sets everything up. 
But then, I agree something with Apple causes issues. 
However, turning it on and off should fix that. 
And Aerial.saver can turn it on and off.

Maybe I need to make a pull request so that you can see what I am talking about?

**Comment by kennyluk** [comment]
Using the newest version on 10.12.4, same issue. However, I fixed it quickly by going into Terminal and changing the permissions to match the other Screensavers.

"chmod og+x Aerial.saver"

**Comment by MichaelDimmitt** [comment]
@kennyluk, interesting. I wonder if that was the cause of the issue. 
potentially all that needs to be changed is the permissions in a pull request. 

Any others find this as a solution that works for them?
<br>Do you really have to use chown? would the chmod command be enough?
`chmod -R og+x Aerial.saver`

**Comment by alistairmcmillan** [comment]
@kennyluk @MichaelDimmitt It's not a permissions issue.

There are multiple versions of Swift. Swift applications including screensavers still include their version of the Swift libraries inside their bundle because of the different versions.

When macOS loads a Swift binary (for example when it loads a screensaver bundle into the System Preferences application) it loads the appropriate Swift libraries for the version of Swift that the binary was compiled against. If you then load another Swift binary (i.e. another screensaver) macOS does not attempt to load the appropriate Swift libraries because it already has Swift libraries loaded. Hence the error message.

You can confirm this by using Activity Monitor to look at the files loaded into the System Preferences application when you have a Swift screensaver selected. When you select a second Swift screensaver that was compiled against a different version you'll see that System Preferences doesn't unload the Swift libraries from the bundle of the first screensaver, they stay loaded and macOS tries and fails to load the second Swift screensaver and link them to those incompatible Swift libraries resulting in the "You cannot use the Aerial screen saver with this version of OS X".

This is a bug in macOS. It is not a permissions problem.

**Comment by diimdeep** [comment]
You have to download Xcode 8 (I tried 8.3.2 in High Sierra) and compile while change compiler to Swift 3.0 
Problem will disapper.

<img width="426" alt="screen shot 2017-12-20 at 00 03 26" src="https://user-images.githubusercontent.com/485713/34178724-429d9d7c-e519-11e7-8fcf-b55465f67a2a.png">

**Comment by glouel** [comment]
Closing as this is solved now thankfully !
