### ISSUE TITLE
Feature request: add a countdown timer (on-screen display) for timing lesson breaks

### ISSUE THREAD

**Issue by Dallas-T** [JohnCoates/Aerial#859]
For anybody delivering classroom-style training workshops, it can be difficult to get everybody back into the room on time.

The best way I've found to do this is to put a countdown timer, in minutes, on-screen. 

It puts the onus on the participant to work out when to be back, so they won't be the one walking in late. 

Everybody knows where they stand by just looking at the screen, even the trainer.

This would also give the screensaver project some free advertising because many people will want to know "where did you get that!"

Bonus features for me would be-

a) allowing tapping the up or down arrow on the keyboard to add or delete minutes
(saves opening the preference box to change time from say the prev. 60min lunch to 15min pm break, just tap or hold up or down key; also allows you to quickly time a class exercise)

b) play a sound when the timer reaches zero
(airplane seatbelt sign turn-on sound ;-)

c) minute display flashes (and or changes colour) when it reaches zero

d) if you could get a screensaver to transmit over a web-meeting from the host's machine, that would be pretty cool for online lessons (maybe this is already a thing, I can't recall)

Love this thing, thank you to the team ⭐️👍😀

Edit- FYI, I use a hot-corner to activate the screen saver.

**Comment by glouel** [comment]
Hi @Dallas-T 

This is a pretty narrow usage scenario. Since I'm pretty much alone developing this, right now I try to prioritize features that benefit the most people. I'll keep this open for the time being.

There are many issues introduced with Catalina that takes priority though. With that said some quick remarks: 

>  allowing tapping the up or down arrow on the keyboard to add or delete minutes

Screen savers in Catalina can no longer access the keyboard (or mouse). 

> if you could get a screensaver to transmit over a web-meeting from the host's machine

What happens in this kind of scenarios depends completely on macOS and whatever streaming software you use. macOS decides to start and stop the screensaver, we have no control as to when/where we are displayed. 

Finally,

> free advertising

This may have not been your intention, but I personally do take a tiny bit of offense to a *very* specific custom request that includes "this" as a reason it should be implemented.

**Comment by Dallas-T** [comment]
@glouel I'm very sorry it wasn't my intention to offend.

My motivation for the enhancement request was to leverage the great work that has already been done by putting it to work, e.g. have the screensaver but include a count down clock so there would be more people looking at the screen saver (and your work).

The need for timers is pretty common in my world of training.

I saw it already had options for adding custom text and displaying a clock so thought a timer might be an extension of this type of thing. 

The 'free advertising' was for the team (you, as you point out). There's no gain in this for me since I already use a countdown timer, but would admit none are as beautiful as your screen saver, so thought I'd ask.

I'm going to buy you a coffee to try and make up for my error :)

If such a feature was added at some point I'd happily buy you 10 coffees. I know that would not be a proper reflection of your time, but as I said, I genuinely thought this feature would be helpful for others directly, and the project indirectly.

Cheers :)

**Comment by glouel** [comment]
Hey no worries, maybe I had a bad morning. Happy to see you didn't intend it this way in any case and no harm done, really. 

Right now I'm still trying to fix auto updates and some hanging bug. As you point out there are already some pretty specific features already that don't appeal to everyone so I'm not against that one per se. 

Practically speaking there's no way to launch the screensaver with say a different hot corner that I could detect (at least I don't think so) that would trigger the timer effect, and anything keyboard is also impossible now. So that would have to go in the UI. 

Still practically speaking the whole text rendering needs to be rewritten to account for some of the requested features (sync multiple computers for example) and fix some tiny rendering bugs, I'll group this one with the logo thing people asked here some time ago : https://github.com/JohnCoates/Aerial/issues/189 and a rework of the custom text thing too. 

But right now priority is on fixing stuff for Catalina so might take a while for me to get to it. In any case sorry if I read your message the wrong way, and thanks a lot for the coffee 👍

**Comment by Dallas-T** [comment]
Thanks glouel 👍 ⭐️

**Comment by glouel** [comment]
Hi @Dallas-T !

It's been a while, but after the rewrite of 1.7.0 I've added a countdown option in the latest beta : https://github.com/JohnCoates/Aerial/releases/download/v1.7.2beta1/Aerial.saver.zip

This is still a work in progress but there are a few features. Here's how it looks right now : 
![Capture d’écran 2020-02-13 à 17 59 19](https://user-images.githubusercontent.com/37544189/74463284-e9ebf180-4e91-11ea-8de5-244465a72b7a.jpg)

There are two distinct modes, "Precise date" and "Time of day". The idea behind "Precise date" is simple, it's a countdown to a given date : 

![Capture d’écran 2020-02-13 à 17 21 25](https://user-images.githubusercontent.com/37544189/74463478-2e778d00-4e92-11ea-9f77-c3f46765a4b1.jpg)

The other mode is a countdown to a specific time of day, for example : 

![Capture d’écran 2020-02-13 à 17 51 18](https://user-images.githubusercontent.com/37544189/74463550-4818d480-4e92-11ea-86fd-d63964f53590.jpg)

Since we can't use the keyboard, I've added a trigger option to try and make it a bit more user friendly. It let's you set a trigger time after which the countdown starts. So let's say you want to make a timer to 14:00, you can then set a trigger at 12:00, so that it will only launch the countdown from 12:00 to 14:00, and not outside of that time window. 

Give the beta a shot and let me know, there are still a few things that can be improved, first one being having multiple options for the format (something like -00:00:35 for example).

**Comment by Dallas-T** [comment]
Hi Guillaume, this is awesome. Thanks so much. ⭐️👍

Do you think it would be possible to have a countdown from a set time? Eg just put in 30 minutes and it counts down to zero from 30 minutes.

I ask Siri to set a timer all the time at home for this and that, and wondering if folks might find having this on their larger computer screens a handy thing.
Its pretty good ATM tho :)


PS. In testing I found the seconds could not be turned off. Understand this is a Beta tho :)






Thank you,


Dallas Tye

dallas.tye@gmail.com
+61 (0)418 219 444

**Comment by glouel** [comment]
> Hi Guillaume, this is awesome. Thanks so much. ⭐️👍 
> Do you think it would be possible to have a countdown from a set time? Eg just put in 30 minutes and it counts down to zero from 30 minutes.

Yep that's an option, I may split it from the countdown and call it a timer, for UI purposes, though. One issue with a fix amount of time is that you'll explicitly need to set it each time, and it will reset each time it's launched. One thing that could be added is maybe a "only run once" option but that's about it for control I fear. 

> I ask Siri to set a timer all the time at home for this and that, and wondering if folks might find having this on their larger computer screens a handy thing. Its pretty good ATM tho :) 

Indeed, although setting it each time in the UI is definitely not super convenient (and just like keyboard access, Siri is very much a non starter for a screensaver too). 

>PS. In testing I found the seconds could not be turned off. Understand this is a Beta tho :) Thank you, Dallas Tye

Yep, still struggling with the formatting, will come in a further beta ;)

**Comment by glouel** [comment]
@Dallas-T 

Here's a new beta with a separate Timer option. It's just as discussed, a simple timer that counts down to 0 from a given timer amount of time :

![Capture d’écran 2020-03-19 à 19 30 01](https://user-images.githubusercontent.com/37544189/77102774-a7ca4880-6a19-11ea-96dc-bdb401f5c8dd.jpg)

Here it's set for 30 mins. 
Couple of options, when elapsed the first one will disable the timer (same thing as unclicking the checkbox at the top of the screen) for subsequent launchs. That makes sure you only run it once and will be a bit easier.

Second one is an option to show a custom message when the timer is elapsed. If you don't check this and put your message, it will start counting down negatively.

The seconds thing is also fixed now in this build. 

https://github.com/JohnCoates/Aerial/releases/download/v1.8.2beta2/Aerial.saver.zip

**Comment by Dallas-T** [comment]
Hi mate, I’m sorry I've taken so long to reply. I had trouble installing the linked version (just my lack of knowledge) and then I got distracted with the end of the world etc (mostly joking). I hope you’re doing ok?

I’ve just installed it and it looks different to your screen shot for the timer. I get no simple timer setting like your screenshot.
(love the addition of the message option)

I’ve attached a screenshot showing the version I downloaded form the link in your email.





Thank you,


Dallas Tye

dallas.tye@gmail.com
+61 (0)418 219 444

**Comment by glouel** [comment]
> Hi mate, I’m sorry I've taken so long to reply. I had trouble installing the linked version (just my lack of knowledge) and then I got distracted with the end of the world etc (mostly joking). I hope you’re doing ok? I’ve just installed it and it looks different to your screen shot for the timer. I get no simple timer setting like your screenshot. (love the addition of the message option) I’ve attached a screenshot showing the version I downloaded form the link in your email. Thank you, Dallas Tye dallas.tye@gmail.com +61 (0)418 219 444
> […](#)

Hi @Dallas-T 

I'm doing ok I guess, starting week 2 of quarantine around here. 

So first, I can't see your screenshot, you can't attach a screenshot by email to github, you have to post it on the website. 

But your issue might just be that you didn't close System Preferences before installing. If that's the case, just close System Preferences (the entire window) by pressing the close button on top : 

![Capture d’écran 2020-03-23 à 13 44 13](https://user-images.githubusercontent.com/37544189/77318019-8d8bb580-6d0c-11ea-9479-b557218f0bff.jpg)

Then reopen it and the new version should be loaded correctly. If it doesn't, post your screenshot and I'll have a look but I double checked on another mac and it loads ok.

**Comment by Dallas-T** [comment]
Hi, installed 1.8.2beta4 and still not seeing as a number field, just the time field with AM/PM option, as per screenshot. (followed your advice regarding installing newer versions to get beta 4 installed)

![image](https://user-images.githubusercontent.com/37423633/77385080-3c96c280-6ddb-11ea-9234-b9e23b650229.png)

**Comment by glouel** [comment]
Hi @Dallas-T !

Ok, I get what you were saying now. The field is still a duration field, it just looks weird because you are in an AM/PM locale and I didn't account for that ;) If you input 00:05:00 AM you should get a 5 minutes timer. 

I'll try to fix the field so it looks proper in your locale too, will get back to you but it should work in the meantime, it's just a cosmetic oddity.

**Comment by glouel** [comment]
Hi again @Dallas-T !

I fixed it, I also fixed the fact that it was filled by default with the current date. Should look much better now ;) 

https://github.com/JohnCoates/Aerial/releases/download/v1.8.2/Aerial.saver.zip

**Comment by Dallas-T** [comment]
Installed, and working perfectly. Thanks so much :)  I've just sent you a barrel of Australian coffee, sorry about the exchange rate with AUD, but as I said in my note, this screen saver is the beauty we all need in our lives ATM. 👍😀⭐️

**Comment by glouel** [comment]
Glad it’s fixed ! And thank you so much, truly appreciated ! And yes Aerial tends to bring a smile to people’s face and we definitely need a lot of that right now ! Take care and best of luck on your business !

**Comment by glouel** [comment]
Closing this with the release, feel free to open another issue if you have another request.
